### ISSUE TITLE
Orientation and visibility of tool bars on mobile devices.

### ISSUE THREAD

**Issue by poetaster** [ffalt/mah#426]
Hi. I'm the person who packages: https://github.com/poetaster/harbour-moremahjong

I've had users request that the tool bars be minimized when in Landscape mode. My users are primarily mobile phone (Sailfish OS) users, so they generally play that way. I'm not sure of the best way to do this, perhaps with a media hint. I had also thought of it becoming a setting. 

And thanks for the contrast changes!

**Comment by poetaster** [comment]
I should mention that fullscreen doesn't work in the QT WebView context. But that is a moving target at the moment since I'm on one minor version less than the current WebView component. As soon as I can test that, maybe I can get fullscreen working. Althought that might have other issues :)

**Comment by ffalt** [comment]
In landscape on small screen I will try moving the bars to to left and right without the labels. 
Tool bars are still in fullscreen, too, so I think this would not help.

**Comment by ffalt** [comment]
Hi there, I [released](https://github.com/ffalt/mah/releases) a new version with this changes (and more optimization which hopefully benefit small screen users).
![bars_leftright](https://user-images.githubusercontent.com/3438714/173509568-9a887cfb-68e6-407d-8071-d5a7b6c2cf4c.png)

**Comment by poetaster** [comment]
This looks really great! I'll give it a shot asap. Thanks!

**Comment by poetaster** [comment]
I've tested and the improvements are great! Thanks!

**Comment by ffalt** [comment]
Great!

I'm currently testing a wrapper for Android Phones, which works fine in general, but sending the mobile app into the background the Android Webview wouldn't send an event to the webpage, so the game could not pause the game & time. I therefor had to integrate some API to the wrapper into the web app with a dedicated build config.

Let me know if we can improve something for Sailfish in this regard.

**Comment by poetaster** [comment]
Ah, the WebView component gets a signal when the app is backgrounded and pauses properly on sailfish. There is a Sailfish bug which kills audio, but that's temporary.

I was thinking of a build for SFOS, Android and Ubuntu touch (possibly also kde plasma). 

What approach are you using to build the Android app? In my case it's all QT. I have some projects with a lot of targets.

**Comment by ffalt** [comment]
I'm evaluating [capacitorjs](https://capacitorjs.com/), it supports only Android and ios.
Since the game webapp does not necessarily need any native features or UI, this works fine and is of very low effort.
https://github.com/ffalt/mah/tree/main/resources/mobile. 
IMO a wrapper for multiple targets would be even better.

**Comment by poetaster** [comment]
> I'm evaluating [capacitorjs](https://capacitorjs.com/), it supports only Android and ios. Since the game webapp does not necessarily need any native features or UI, this works fine and is of very low effort. https://github.com/ffalt/mah/tree/main/resources/mobile. IMO a wrapper for multiple targets would be even better.

My package is a pure QML wrapper made, more or less, one component: https://doc.qt.io/qt-6/qtwebview-index.html
I'll have a look next week.
