### ISSUE TITLE
Mah for Ubuntu Touch 20.04

### ISSUE THREAD

**Issue by Alter2020** [ffalt/mah#440]
I like this game a lot and noticed it's not in OpenStore for UT 20.04. Is it possible for you to make a release?
In any case, thanks for the app. I used it a lot in 16.04.

**Comment by ffalt** [comment]
Hi! Thank you! I'm happy that you like Mah.

Unfortunatly I have very little knowledge about the Ubuntu OpenStore.

Could you please ask the maintainer if they can add it to 20.04 store?
https://open-store.io/app/net.gsantner.ut.mahjonggmah
https://gsantner.net/page/about.html

**Comment by Alter2020** [comment]
Yes, thank you. Just contacted him!
