### ISSUE TITLE
Adjust to screen size

### ISSUE THREAD

**Issue by piranna** [ffalt/mah#74]
CUrrently board size is fixed, so it gets small in big screens. Allow to scale it to actual screen size.

**Comment by ffalt** [comment]
hi! no, board size is not fixed and it should scale, so this may be a bug. 
testing in chrome with e.g. 6000x4000 
![screenshot](https://user-images.githubusercontent.com/3438714/53871095-d2f31d00-3ffb-11e9-8805-ba29c46e44af.jpg)
which browser/OS/screen sizes do you use?

**Comment by piranna** [comment]
Ah, ok, I got confused by the initial board selector, that it was shown too much small, sorry. Maybe could it be scaled too, then?

**Comment by ffalt** [comment]
dialogs & overlays are much larger now on large screens in v1.1.0
